on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: abystoma/external-workflow
         
          
      - name: Greeting
        run: echo "$(<greeting.txt)"
